import { createClient } from "@/lib/supabase/server";
import { NextResponse } from "next/server";

// Define admin IDs
const ADMINS = [
  "7a74fc41-af12-4c71-9892-dd71e2db0b0b", // Add your admin ID here
];

async function checkAdminAuth() {
  const supabase = createClient();
  const { data: { user }, error } = await supabase.auth.getUser();
  
  if (error || !user) {
    return NextResponse.json({ error: "未授權" }, { status: 401 });
  }
  
  if (!ADMINS.includes(user.id)) {
    return NextResponse.json({ error: "權限不足" }, { status: 403 });
  }
  
  return null;
}

export async function GET() {
  const authError = await checkAdminAuth();
  if (authError) return authError;

  try {
    // Mock email campaigns data for now
    const campaigns = [
      {
        id: 1,
        title: "新用戶歡迎郵件",
        subject: "歡迎加入 RenderResume！",
        type: "welcome",
        status: "active",
        recipientCount: 1250,
        openRate: 45.2,
        clickRate: 12.8,
        createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        sentAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 2,
        title: "Premium 功能介紹",
        subject: "解鎖更多強大功能 - 升級至 Premium",
        type: "promotional",
        status: "sent",
        recipientCount: 3420,
        openRate: 38.7,
        clickRate: 8.9,
        createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        sentAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
      },
      {
        id: 3,
        title: "月度功能更新",
        subject: "RenderResume 十二月更新 - 全新模板上線",
        type: "newsletter",
        status: "draft",
        recipientCount: 0,
        openRate: 0,
        clickRate: 0,
        createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
        sentAt: null,
      },
      {
        id: 4,
        title: "用戶回饋調查",
        subject: "幫助我們改進 - 用戶體驗調查",
        type: "survey",
        status: "sent",
        recipientCount: 2100,
        openRate: 52.1,
        clickRate: 15.6,
        createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        sentAt: new Date(Date.now() - 18 * 24 * 60 * 60 * 1000).toISOString(),
      }
    ];

    return NextResponse.json(campaigns);
  } catch (error) {
    console.error("Error fetching campaigns:", error);
    return NextResponse.json({ error: "獲取活動數據失敗" }, { status: 500 });
  }
}

export async function POST(request: Request) {
  const authError = await checkAdminAuth();
  if (authError) return authError;

  try {
    const body = await request.json();
    const { title, type, subject, targetAudience, content } = body;

    // Validate required fields
    if (!title || !type || !subject || !targetAudience || !content) {
      return NextResponse.json({ error: "請填寫所有必填欄位" }, { status: 400 });
    }

    // Create new campaign (mock implementation)
    const newCampaign = {
      id: Date.now(), // In real app, this would be generated by database
      title,
      subject,
      type,
      status: "draft",
      recipientCount: 0,
      openRate: 0,
      clickRate: 0,
      createdAt: new Date().toISOString(),
      sentAt: null,
      targetAudience,
      content,
    };

    // In a real implementation, you would save this to your database
    // const supabase = createClient();
    // const { data, error } = await supabase
    //   .from('campaigns')
    //   .insert([newCampaign])
    //   .select()
    //   .single();

    return NextResponse.json(newCampaign, { status: 201 });
  } catch (error) {
    console.error("Error creating campaign:", error);
    return NextResponse.json({ error: "創建活動失敗" }, { status: 500 });
  }
}

export async function PUT(request: Request) {
  const authError = await checkAdminAuth();
  if (authError) return authError;

  try {
    const body = await request.json();
    const { id, status } = body;

    if (!id || !status) {
      return NextResponse.json({ error: "缺少必要參數" }, { status: 400 });
    }

    // In real implementation, update campaign in database
    // const supabase = createClient();
    // const { data, error } = await supabase
    //   .from('campaigns')
    //   .update({ status })
    //   .eq('id', id)
    //   .select()
    //   .single();

    return NextResponse.json({ success: true, id, status });
  } catch (error) {
    console.error("Error updating campaign:", error);
    return NextResponse.json({ error: "更新活動失敗" }, { status: 500 });
  }
}

export async function DELETE(request: Request) {
  const authError = await checkAdminAuth();
  if (authError) return authError;

  try {
    const { searchParams } = new URL(request.url);
    const id = searchParams.get('id');

    if (!id) {
      return NextResponse.json({ error: "缺少活動 ID" }, { status: 400 });
    }

    // In real implementation, delete campaign from database
    // const supabase = createClient();
    // const { error } = await supabase
    //   .from('campaigns')
    //   .delete()
    //   .eq('id', id);

    return NextResponse.json({ success: true, id });
  } catch (error) {
    console.error("Error deleting campaign:", error);
    return NextResponse.json({ error: "刪除活動失敗" }, { status: 500 });
  }
} 